---
- name: Create Keycloak group
  group:
    name: "{{ keycloak_service_group }}"
    system: true
  become: true

- name: Create Keycloak user
  user:
    name: "{{ keycloak_service_user }}"
    group: "{{ keycloak_service_group }}"
    home: "{{ keycloak_base_path }}"
    create_home: true
    system: true
  become: true

- import_tasks: "install.yml"
  become: true

- import_tasks: "configure.yml"
  become: true
